"""Bake the primer's markdown into one reader page, index.html, at the primer root.

The page has a landing view (chapter cards, a link to the instruments) and a
lesson view (left panel of lessons, rendered markdown with MathJax, a link to
the chapter's station in viz/). The markdown is embedded as JSON, so the page
opens straight from disk with no server. Rerun this after any chapter edit.

Run from the workspace root, with <folder> the primer folder:
    .venv/bin/python <folder>/viz/build_reader.py          # write <folder>/index.html
    .venv/bin/python <folder>/viz/build_reader.py --check  # exit 1 if index.html is stale
"""
import json
import os
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "index.html"
EXTRAS = [("plan", "README.md", "Course plan"), ("exercises", "exercises/README.md", "Exercises"),
          ("resources", "resources.md", "Resources")]


def title_of(md, fallback):
    m = re.search(r"^# (.+)$", md, re.M)
    return m.group(1).strip() if m else fallback


def chapter_table(readme):
    """Map chapter file name to (question, time) from the README chapter table."""
    rows = {}
    for line in readme.splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) == 4 and re.fullmatch(r"`\d\d-[^`]+\.md`", cells[1]):
            rows[cells[1].strip("`")] = (cells[2], cells[3])
    return rows


def intro_of(readme):
    """First paragraph after the H1 that is not the date/status line."""
    body = readme.split("\n", 1)[1] if readme.startswith("# ") else readme
    for para in re.split(r"\n\s*\n", body):
        para = para.strip()
        if para and not para.startswith(("Date:", "#", "|", "```")):
            return para
    return ""


def code_links(doc_base, md):
    """Inline-code spans that name an existing file or folder, mapped to a path from the root."""
    links = {}
    for span in re.findall(r"`([^`\n]+)`", md):
        path = re.sub(r":\d+(-\d+)?$", "", span.strip())
        if not re.fullmatch(r"[\w./-]+", path) or not re.search(r"[A-Za-z]", path) or "/" not in path and "." not in path:
            continue
        target = (ROOT / doc_base / path).resolve()
        if target.exists():
            links[span] = pathlib.Path(os.path.relpath(target, ROOT)).as_posix() + ("/" if target.is_dir() else "")
    return links


def collect():
    readme = (ROOT / "README.md").read_text()
    table = chapter_table(readme)
    docs = []
    for path in sorted(ROOT.glob("[0-9][0-9]-*.md")):
        md = path.read_text()
        q, t = table.get(path.name, ("", ""))
        docs.append({"key": "c" + path.name[:2], "num": path.name[:2], "file": path.name, "base": "",
                     "title": re.sub(r"^\d+\.\s*", "", title_of(md, path.stem)), "question": q, "time": t, "md": md})
    for key, rel, label in EXTRAS:
        path = ROOT / rel
        if path.exists():
            md = path.read_text()
            docs.append({"key": key, "num": "", "file": rel, "base": str(pathlib.Path(rel).parent).strip("."),
                         "title": label, "question": "", "time": "", "md": md})
    for d in docs:
        d["codeLinks"] = code_links(d["base"], d["md"])
    viz = sorted(p for p in (ROOT / "viz").glob("*.html"))
    return {"title": title_of(readme, ROOT.name), "intro": intro_of(readme), "folder": ROOT.name,
            "viz": f"viz/{viz[0].name}" if viz else "", "docs": docs}


def build():
    content = collect()
    data = json.dumps(content, ensure_ascii=False).replace("</", "<\\/")
    return TEMPLATE.replace("__TITLE__", content["title"].replace("<", "&lt;")).replace("__DATA__", data)


TEMPLATE = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>__TITLE__</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Sans+Condensed:wght@500;600&family=IBM+Plex+Sans:wght@400;500;600&display=swap">
<style>
/* Generated by viz/build_reader.py. Edit the script, not this file. */
:root{
  --bg:#f3f4f1; --panel:#fbfbf9; --ink:#1c2228; --muted:#5b6670; --rule:#d6dad8; --grid:#e6e9e6;
  --accent:#245d86; --soft:#e9eef1; --codebg:#eef0ec;
  --display:"IBM Plex Sans Condensed","Arial Narrow",system-ui,sans-serif;
  --body:"IBM Plex Sans",system-ui,-apple-system,"Segoe UI",sans-serif;
  --mono:"IBM Plex Mono",ui-monospace,"SFMono-Regular",Menlo,monospace;
}
@media (prefers-color-scheme: dark){:root:not([data-theme="light"]){
  --bg:#11161a; --panel:#171d22; --ink:#e2e7ea; --muted:#93a0a9; --rule:#2b343b; --grid:#202930;
  --accent:#73b2df; --soft:#1d262d; --codebg:#1b2228; color-scheme:dark}}
:root[data-theme="dark"]{
  --bg:#11161a; --panel:#171d22; --ink:#e2e7ea; --muted:#93a0a9; --rule:#2b343b; --grid:#202930;
  --accent:#73b2df; --soft:#1d262d; --codebg:#1b2228; color-scheme:dark}
*{box-sizing:border-box}
html{scroll-padding-top:16px}
body{background:var(--bg);color:var(--ink);font:16px/1.6 var(--body);margin:0;padding:20px 16px 48px}
a{color:var(--accent)}
.wrap{max-width:1500px;margin:0 auto;display:grid;grid-template-columns:250px minmax(0,1fr);gap:22px;align-items:start}
nav{position:sticky;top:12px;max-height:calc(100vh - 24px);overflow:auto;background:var(--panel);border:1px solid var(--rule);border-radius:6px;padding:8px}
nav .navhead{font:500 11px/1 var(--mono);letter-spacing:.08em;text-transform:uppercase;color:var(--muted);padding:10px 8px 6px}
nav a{display:grid;grid-template-columns:2.2em minmax(0,1fr);gap:4px;align-items:baseline;padding:6px 8px;border-radius:4px;color:var(--ink);text-decoration:none;font-size:14px;line-height:1.3}
nav a:hover{background:var(--soft)}
nav a .n{font:500 12px var(--mono);color:var(--muted);font-variant-numeric:tabular-nums}
nav a[aria-current="page"]{background:var(--accent);color:var(--bg)}
nav a[aria-current="page"] .n{color:var(--bg)}
nav a.out .n{color:var(--accent)}
nav .menu{display:none}
@media (max-width:900px){
  .wrap{grid-template-columns:minmax(0,1fr)}
  nav{position:static;max-height:none}
  nav .menu{display:block;width:100%;font:500 14px var(--body);background:transparent;color:var(--ink);border:0;text-align:left;padding:6px 8px;cursor:pointer}
  nav:not(.open) .links{display:none}
}
main{min-width:0}
.home h1{font:600 clamp(1.8rem,3.6vw,2.6rem)/1.1 var(--display);margin:.2rem 0 .6rem;text-wrap:balance}
.home .intro{max-width:72ch;color:var(--muted);margin:0 0 1rem}
.actions{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 1.4rem}
.btn{display:inline-block;font:500 14px var(--body);text-decoration:none;border:1px solid var(--rule);background:var(--panel);color:var(--ink);border-radius:4px;padding:8px 12px}
.btn.primary{background:var(--accent);border-color:var(--accent);color:var(--bg)}
.btn:hover{border-color:var(--accent)}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:12px}
.card{display:grid;gap:6px;align-content:start;background:var(--panel);border:1px solid var(--rule);border-radius:6px;padding:12px 14px;color:var(--ink);text-decoration:none}
.card:hover{border-color:var(--accent)}
.card .top{display:flex;justify-content:space-between;gap:8px;font:500 12px var(--mono);color:var(--muted)}
.card h3{font:600 1.05rem/1.25 var(--display);margin:0;text-wrap:balance}
.card p{margin:0;font-size:14px;line-height:1.45;color:var(--muted)}
.section-head{font:500 11px/1 var(--mono);letter-spacing:.08em;text-transform:uppercase;color:var(--muted);margin:1.6rem 0 .6rem}
.lesson{display:grid;grid-template-columns:minmax(0,1fr) 220px;gap:28px;align-items:start}
@media (max-width:1250px){.lesson{grid-template-columns:minmax(0,1fr)} .toc{display:none}}
.bar{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:8px;margin-bottom:6px}
.eyebrow{font:500 11px/1 var(--mono);letter-spacing:.08em;text-transform:uppercase;color:var(--muted)}
article{background:var(--panel);border:1px solid var(--rule);border-radius:6px;padding:8px clamp(16px,3vw,40px) 24px;min-width:0}
article>*{max-width:80ch}
article h1{font:600 clamp(1.6rem,3vw,2.2rem)/1.15 var(--display);margin:1rem 0 .8rem;text-wrap:balance}
article h2{font:600 1.45rem/1.2 var(--display);margin:2rem 0 .6rem;padding-top:.6rem;border-top:1px solid var(--grid)}
article h3{font:600 1.15rem/1.25 var(--display);margin:1.4rem 0 .4rem}
article p,article li{max-width:80ch}
article code{font:.88em var(--mono);background:var(--codebg);padding:.08em .3em;border-radius:3px;overflow-wrap:anywhere}
article a code{color:var(--accent)}
article pre{background:var(--codebg);border-radius:5px;padding:10px 12px;overflow-x:auto;max-width:none}
article pre code{background:none;padding:0;font-size:13px;line-height:1.5;overflow-wrap:normal}
article table{border-collapse:collapse;display:block;overflow-x:auto;max-width:100%;font-size:14px;margin:1rem 0}
article th,article td{border:1px solid var(--rule);padding:5px 8px;vertical-align:top;text-align:left}
article th{background:var(--soft);font-weight:600}
article blockquote{margin:1rem 0;padding:.2rem 1rem;border-left:3px solid var(--accent);background:var(--soft);border-radius:0 4px 4px 0}
.mathd{display:block;overflow-x:auto;overflow-y:hidden;margin:.8rem 0;text-align:center}
.mathi mjx-container{display:inline-block}
mjx-container[jax="SVG"]>svg{overflow:visible}
.tex-raw{font:13px var(--mono);color:var(--muted)}
.toc{position:sticky;top:12px;max-height:calc(100vh - 24px);overflow:auto;font-size:13px;line-height:1.35}
.toc a{display:block;padding:4px 8px;border-left:2px solid var(--rule);color:var(--muted);text-decoration:none}
.toc a:hover{color:var(--ink);border-left-color:var(--accent)}
.toc a.h3{padding-left:18px}
.toc code{font:.95em var(--mono)}
.card code{font:.9em var(--mono)}
.pager{display:flex;justify-content:space-between;gap:12px;margin-top:16px}
.pager a{flex:1 1 0;max-width:48%}
.pager .next{text-align:right;margin-left:auto}
footer{color:var(--muted);font-size:13px;margin-top:2rem;max-width:80ch}
</style>
</head>
<body>
<div class="wrap">
<nav id="nav" aria-label="Lessons"></nav>
<main id="main"></main>
</div>
<script id="data" type="application/json">__DATA__</script>
<script>
window.MathJax = {
  tex: { inlineMath: [], displayMath: [] },
  svg: { fontCache: "local" },
  options: { enableMenu: false },
  startup: { typeset: false, ready() { MathJax.startup.defaultReady(); MathJax.startup.promise.then(() => { mathReady = true; typesetMath(); }); } }
};
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/18.0.14/lib/marked.umd.min.js"></script>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-svg-full.js"></script>
<script>
const DATA = JSON.parse(document.getElementById("data").textContent);
const DOCS = DATA.docs, BY = Object.fromEntries(DOCS.map(d => [d.key, d]));
const BYFILE = Object.fromEntries(DOCS.map(d => [d.file, d]));
const $ = id => document.getElementById(id);
let mathReady = false;
const esc = s => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const store = { get(k) { try { return localStorage.getItem(k); } catch (e) { return null; } },
                set(k, v) { try { localStorage.setItem(k, v); } catch (e) {} } };

// Markdown with TeX: hide math from marked behind private-use placeholders, then put it back.
function renderMarkdown(md) {
  const math = [], code = [];
  const lines = md.split("\n"), out = []; let fence = null, chunk = [];
  const flush = () => { out.push(protect(chunk.join("\n"))); chunk = []; };
  function protect(text) {
    text = text.replace(/(`+)([^`]|[^`][\s\S]*?[^`])\1(?!`)/g, m => "" + (code.push(m) - 1) + "");
    text = text.replace(/\$\$([\s\S]+?)\$\$/g, (m, t) => "D" + (math.push([t, true]) - 1) + "");
    text = text.replace(/(^|[^\\$])\$(?!\s)((?:\\\$|[^$\n])+?)(?<![\s\\])\$(?!\d)/g,
      (m, pre, t) => pre + "I" + (math.push([t, false]) - 1) + "");
    return text.replace(/(\d+)/g, (m, i) => code[+i]);
  }
  for (const line of lines) {
    const f = /^\s*(`{3,}|~{3,})/.exec(line);
    if (fence) { out.push(line); if (f && f[1][0] === fence[0] && f[1].length >= fence.length) fence = null; continue; }
    if (f) { flush(); fence = f[1]; out.push(line); continue; }
    chunk.push(line);
  }
  flush();
  const html = marked.parse(out.join("\n"), { gfm: true });
  return html.replace(/([DI])(\d+)/g, (m, k, i) =>
    `<span class="${k === "D" ? "mathd" : "mathi"}" data-tex="${esc(math[+i][0])}">${esc(math[+i][0])}</span>`);
}
function typesetMath() {
  if (!mathReady) return;
  if (!document.getElementById("mjx-svg-css")) { const css = MathJax.svgStylesheet(); css.id = "mjx-svg-css"; document.head.append(css); }
  document.querySelectorAll("[data-tex]:not([data-done])").forEach(el => {
    try { el.replaceChildren(MathJax.tex2svg(el.dataset.tex, { display: el.classList.contains("mathd") })); }
    catch (e) { el.classList.add("tex-raw"); }
    el.dataset.done = "1";
  });
}

function resolve(base, href) {
  const parts = (base ? base + "/" + href : href).split("/"), outp = [];
  for (const p of parts) { if (p === "..") { if (outp.length && outp[outp.length - 1] !== "..") outp.pop(); else outp.push(p); } else if (p !== ".") outp.push(p); }
  return outp.join("/");
}
function fixLinks(root, doc) {
  root.querySelectorAll("a[href]").forEach(a => {
    const href = a.getAttribute("href");
    if (/^[a-z]+:/i.test(href)) { a.target = "_blank"; a.rel = "noopener"; return; }
    if (href.startsWith("#")) { a.onclick = e => { e.preventDefault(); const t = document.getElementById(href.slice(1)); if (t) t.scrollIntoView(); }; return; }
    const [path, frag] = href.split("#"), target = resolve(doc.base, path);
    if (BYFILE[target]) a.href = "#" + BYFILE[target].key;
    else a.href = target + (frag ? "#" + frag : "");
  });
  root.querySelectorAll("code").forEach(c => {
    if (c.closest("pre, a")) return;
    const text = c.textContent;
    const md = BYFILE[resolve(doc.base, text)];
    const href = md ? "#" + md.key : doc.codeLinks[text];
    if (!href) return;
    const a = document.createElement("a"); a.href = href; c.replaceWith(a); a.append(c);
  });
}
function slug(s) { return s.toLowerCase().replace(/<[^>]+>/g, "").replace(/[^\w\s-]/g, "").trim().replace(/\s+/g, "-"); }

function navHTML(current) {
  const item = (key, n, label) => `<a href="#${key}"${key === current ? ' aria-current="page"' : ""}><span class="n">${n}</span><span>${esc(label)}</span></a>`;
  let h = `<button class="menu" type="button" onclick="this.parentNode.classList.toggle('open')">Lessons</button><div class="links">`;
  h += item("home", "⌂", "Home");
  h += `<div class="navhead">Chapters</div>` + DOCS.filter(d => d.num).map(d => item(d.key, d.num, d.title)).join("");
  h += `<div class="navhead">Course</div>` + DOCS.filter(d => !d.num).map(d => item(d.key, "·", d.title)).join("");
  if (DATA.viz) h += `<div class="navhead">Interactive</div><a class="out" href="${DATA.viz}"><span class="n">▶</span><span>Instruments</span></a>`;
  return h + "</div>";
}
function vizLink(doc) { return DATA.viz && doc.num && doc.num !== "00" ? `${DATA.viz}#s${doc.num}` : ""; }

function showHome() {
  const chapters = DOCS.filter(d => d.num), last = store.get("reader:last");
  const lastDoc = last && BY[last];
  const card = d => `<a class="card" href="#${d.key}"><div class="top"><span>${d.num ? "Chapter " + d.num : "Course"}</span><span>${esc(d.time)}</span></div><h3>${esc(d.title)}</h3>${d.question ? `<p>${marked.parseInline(d.question)}</p>` : ""}</a>`;
  $("main").innerHTML = `<section class="home">
    <div class="eyebrow">${esc(DATA.folder)}</div>
    <h1>${esc(DATA.title)}</h1>
    <p class="intro" id="intro"></p>
    <div class="actions">
      <a class="btn primary" href="#${(lastDoc || chapters.find(d => d.num === "01") || chapters[0]).key}">${lastDoc ? "Continue: " + esc(lastDoc.title) : "Start with chapter 01"}</a>
      ${DATA.viz ? `<a class="btn" href="${DATA.viz}">Open the instruments</a>` : ""}
      ${BY.plan ? `<a class="btn" href="#plan">Course plan</a>` : ""}
    </div>
    <div class="section-head">Chapters</div>
    <div class="grid">${chapters.map(card).join("")}</div>
    <div class="section-head">Course material</div>
    <div class="grid">${DOCS.filter(d => !d.num).map(card).join("")}</div>
    <footer>Generated from the markdown files by <code>viz/build_reader.py</code>. Run it again after a chapter changes. Math renders with MathJax and markdown with marked, both from a CDN.</footer>
  </section>`;
  $("intro").innerHTML = marked.parseInline(DATA.intro);
}
function showDoc(doc) {
  store.set("reader:last", doc.key);
  const order = DOCS, i = order.indexOf(doc), prev = order[i - 1], next = order[i + 1];
  const viz = vizLink(doc);
  $("main").innerHTML = `<div class="lesson"><div>
      <div class="bar"><span class="eyebrow">${doc.num ? "Chapter " + doc.num : "Course"} · ${esc(doc.file)}</span>
        ${viz ? `<a class="btn" href="${viz}">Open this chapter's instrument</a>` : ""}</div>
      <article id="article">${renderMarkdown(doc.md)}</article>
      <div class="pager">${prev ? `<a class="btn" href="#${prev.key}">← ${esc(prev.title)}</a>` : ""}${next ? `<a class="btn next" href="#${next.key}">${esc(next.title)} →</a>` : ""}</div>
    </div><aside class="toc" id="toc" aria-label="On this page"></aside></div>`;
  const art = $("article");
  fixLinks(art, doc);
  const heads = [...art.querySelectorAll("h2, h3")];
  heads.forEach(h => { if (!h.id) h.id = slug(h.textContent); });
  $("toc").innerHTML = `<div class="eyebrow" style="padding:0 8px 8px">On this page</div>` +
    heads.map(h => `<a class="${h.tagName.toLowerCase()}" href="#${h.id}">${h.innerHTML}</a>`).join("");
  $("toc").querySelectorAll("a").forEach(a => a.onclick = e => { e.preventDefault(); document.getElementById(a.getAttribute("href").slice(1)).scrollIntoView(); });
  typesetMath();
  window.scrollTo(0, 0);
}
function route() {
  const key = location.hash.slice(1) || "home", doc = BY[key];
  $("nav").innerHTML = navHTML(doc ? key : "home");
  if (doc) { document.title = doc.title + " · " + DATA.title; showDoc(doc); }
  else { document.title = DATA.title; showHome(); }
}
window.addEventListener("hashchange", route);
route();
</script>
</body>
</html>
"""

if __name__ == "__main__":
    html = build()
    if "--check" in sys.argv[1:]:
        if not OUT.exists() or OUT.read_text() != html:
            print(f"{OUT.relative_to(ROOT.parent)} is stale. Run viz/build_reader.py.")
            sys.exit(1)
        print(f"{OUT.relative_to(ROOT.parent)} is up to date.")
    else:
        OUT.write_text(html)
        print(f"wrote {OUT.relative_to(ROOT.parent)} ({len(html) // 1024} KB)")
